/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto000Pdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto000Pdf) 

 RooCFAuto000Pdf::RooCFAuto000Pdf(const char *name, const char *title, 
                        RooAbsReal& _t1,
                        RooAbsReal& _t2,
                        RooAbsReal& _GammaS) :
   RooAbsPdf(name,title), 
   t1("t1","t1",this,_t1),
   t2("t2","t2",this,_t2),
   GammaS("GammaS","GammaS",this,_GammaS)
 { 
 } 


 RooCFAuto000Pdf::RooCFAuto000Pdf(const RooCFAuto000Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   t1("t1",this,other.t1),
   t2("t2",this,other.t2),
   GammaS("GammaS",this,other.GammaS)
 { 
 } 



 Double_t RooCFAuto000Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return exp(-GammaS*(t1+t2)) ; 
 } 



